name: release

on:
  push:
    tags:
      - 'v*'
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
        token: ${{ secrets.GITHUB_TOKEN }}
        submodules: true

    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14

    - name: build
      run: go build -o test main.go && sha256sum test > test.sha256sum

    - name: Release name
      id: release_name
      run: |
        python .github/workflows/get_release_name.py

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: release-${{ steps.release_name.outputs.RELEASE_NAME }}
        release_name: Release ${{ steps.release_name.outputs.RELEASE_NAME }}
        draft: false
        prerelease: false
        
    - name: Upload Release Asset (binary)
      id: upload-release-asset 
      uses: AButler/upload-release-assets@v2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: test*
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        release-tag: release-${{ steps.release_name.outputs.RELEASE_NAME }}
