name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
        token: ${{ secrets.GITHUB_TOKEN }}
        submodules: true

    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14

    - name: build
      run: go build -o test main.go && sha256sum test > test.sha256sum

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        
    - name: Upload Release Asset (binary)
      id: upload-release-asset 
      uses: AButler/upload-release-assets@v2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: test*
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        release-tag: ${{ github.ref }}
